### ISSUE TITLE
encode bug

### ISSUE THREAD

**Issue by MyGitHub5** [grafi-tt/lunajson#36] opened 2021-04-21 02:28 UTC
encode empty table to {} instead of []

**Comment by tst2005** [comment] 2021-04-21 10:48
I think is it not a bug but a problem.
In Lua everything is a table, both array data and objet data are lua table,
then empty table can be both empty array or empty objet.
It seems to detect if the empty lua table should be encoded as empty JSON array or empty JSON object.

**Comment by MyGitHub5** [comment] 2021-04-22 01:56
You're right.
In this it is good but much slower
http://regex.info/blog/lua/json

**Comment by grafi-tt** [comment] 2024-03-14 03:17
It's Lua limitation so I'll close the issue. Note that you can encode an empty array by lunajson by setting the array length as 0-th element. 

```
local a = {}
a[0] = 0`
```

**Closed by grafi-tt** 2024-03-14 03:17 UTC
